name: Deploy to Environment - Vehiculos # prueba

on:
  push:
    tags:
      - 'dev-*'
      - 'test-*'
      - 'prod-*'

jobs:
  extract-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.env }}
    steps:
      - name: Extract environment from tag
        id: set_env
        run: |
          ENVIRONMENT=$(echo "${GITHUB_REF_NAME}" | cut -d'-' -f1)
          echo "env=$ENVIRONMENT" >> $GITHUB_OUTPUT

  deploy:
    needs: extract-env
    runs-on: ubuntu-latest
    environment: ${{ needs.extract-env.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            lusalvi/vehiculos:${{ github.ref_name }}
            lusalvi/vehiculos:${{ needs.extract-env.outputs.environment }}

      - name: Notificar a Render
        if: startsWith(github.ref_name, 'prod-')
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_VEHICULOS }}